// Objective-C API for talking to github.com/antoine-richard/iosapp-swift-golang/golang-lib Go package.
//   gobind -lang=objc -prefix=Go github.com/antoine-richard/iosapp-swift-golang/golang-lib
//
// File is generated by gobind. Do not edit.

#ifndef __GoWeather_H__
#define __GoWeather_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoWeatherCityWeather;

@interface GoWeatherCityWeather : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)city;
- (void)setCity:(NSString*)v;
- (NSString*)description;
- (void)setDescription:(NSString*)v;
- (long)temperature;
- (void)setTemperature:(long)v;
@end

FOUNDATION_EXPORT BOOL GoWeatherFetchByName(NSString* city, GoWeatherCityWeather** ret0_, NSError** error);

#endif
