// Objective-C API for talking to github.com/antoine-richard/iosapp-swift-golang/golang-lib Go package.
//   gobind -lang=objc -prefix=Go github.com/antoine-richard/iosapp-swift-golang/golang-lib
//
// File is generated by gobind. Do not edit.

#ifndef __GoWeather_H__
#define __GoWeather_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoWeatherCityWeather;

@interface GoWeatherCityWeather : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)city1Name;
- (void)setCity1Name:(NSString*)v;
- (NSString*)city1Desc;
- (void)setCity1Desc:(NSString*)v;
- (NSString*)city1Temp;
- (void)setCity1Temp:(NSString*)v;
- (NSString*)city2Name;
- (void)setCity2Name:(NSString*)v;
- (NSString*)city2Desc;
- (void)setCity2Desc:(NSString*)v;
- (NSString*)city2Temp;
- (void)setCity2Temp:(NSString*)v;
- (NSString*)city3Name;
- (void)setCity3Name:(NSString*)v;
- (NSString*)city3Desc;
- (void)setCity3Desc:(NSString*)v;
- (NSString*)city3Temp;
- (void)setCity3Temp:(NSString*)v;
@end

FOUNDATION_EXPORT BOOL GoWeatherFetch(GoWeatherCityWeather** ret0_, NSError** error);

#endif
