// Objective-C API for talking to github.com/antoine-richard/iosapp-swift-golang/golang-lib Go package.
//   gobind -lang=objc -prefix=Go github.com/antoine-richard/iosapp-swift-golang/golang-lib
//
// File is generated by gobind. Do not edit.

#ifndef __GoWeather_H__
#define __GoWeather_H__

#include <Foundation/Foundation.h>

@class GoWeatherWeather;

@interface GoWeatherWeather : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)text;
- (void)setText:(NSString*)v;
- (int)temperature;
- (void)setTemperature:(int)v;
@end

FOUNDATION_EXPORT GoWeatherWeather* GoWeatherFetch();

#endif
