
// Objective-C API for talking to the following Go packages
//
//	github.com/antoine-richard/iosapp-swift-golang/golang-lib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Weather_H__
#define __Weather_H__

#include "GoWeather.h"
#include "GoUniverse.h"

#endif
